#AnarchyCore plugin developed by danimania
#GitHub link: https://github.com/banimania/AnarchyCore
#Discord link: https://discord.gg/nVXAWYJ256

#Global settings for the plugin
global:
  #Name shown in tab
  name: "AnarchyCore"
  #Prefix shown on commands and messages from the plugin
  prefix: "&f[&3&lAnarchyCore&f] "
  #Info shown on joining and in the tab
  news: "[AnarchyCore] Change this in config.yml!"
  #No-permission message
  no-permission-message: "&cYou're not allowed to do this!"

#Command whitelist
#When a normal player runs a command, if it's not on this list, it will return a specified message.
command-whitelist:
  enabled: true
  whitelist-message: "&fUnknown command. Type \"/help\" for help."
  whitelisted-commands:
    - "help"
    - "tps"
    - "ignore"
    - "ignorelist"
    - "w"
    - "msg"
    - "tell"
    - "r"
    - "reply"
    - "w"
    - "l"
    - "last"
    - "pm"
    - "tell"
    - "togglemsgs"
    - "togglejoinmsgs"
    - "togglechat"
    - "toggledeathmsgs"
    - "stats"
    - "kill"
    - "ping"
    - "bed"
    - "joindate"
    - "dmt"
    - "discord"
    - "nc"

#Manage the enabled commands
enabled-commands:
  #Set a command to false to fully disable it. Also check command whitelist config above.
  help: true
  bed: true
  discord: true
  stats: true
  joindate: true
  ping: true
  toggledeathmsgs: true
  togglejoinmsgs: true
  corereload: true
  kill: true
  nc: true
  ignore: true
  ignorelist: true

#Manage the plugin permissions
permissions:
  corereload: "anarchycore.corereload"
  nc: "anarchycore.nc"
  nc-format: "anarchycore.nc-format"
  bypass-whitelist: "anarchycore.bypasswhitelist"
  bypass-illegals: "anarchycore.bypassillegals"

#Manage MOTD messages (not in-game MOTD)
motd:
  enabled: true
  #A MOTD will be displayed randomly
  motd-list:
    - "Motd Test\nNumber one"
    - "Motd Test\nNumber two"
    - "Motd Test\nNumber three"
    - "Motd Test\nNumber four"
    - "Motd Test\nNumber five"

#Manage welcome message
welcome-message:
  #If show is on 1, it will show only on FIRST join. If show is on 2, it will show always on join. If show is on 3, it will not show to anyone.
  show: 1
  message: "&bWelcome &6<player> &bto this anarchy server! There are &6<connected>/<maxplayers> &bplayers connected. Use /help to show commands."

#Links of the server
links:
  discord: "yourserver.com/discord"
  discord-message: "&6Join our Discord server: &c"

#Configuration about the join messages
join-messages:
  #Disable this if you want to use another join/leave messages plugin or want to leave it as default.
  enabled: true
  #Messages
  join: "&f<player> &bjoined the game"
  leave: "&f<player> &bleft the game"
  #Messages of /togglejoinmsgs
  muted: "&bYou won't see join/leave messages anymore."
  unmuted: "&bYou now will see join/leave messages."

ignore-command:
  usage: "&bYou need to specify the name of the player you want to ignore. Usage: /ignore <player>"
  ignored: "&bYou have successfully ignored &c<player>!"
  unignored: "&bYou have successfully unignored &c<player>!"
  player-doesntexist: "&bSpecified player doesn't exist"

ignorelist-command:
  message: "&bIgnored players: &7<list>"

#Configuration about the death messages
death-messages:
  #Disable this if you want to use another death messages plugin or want to leave it as default.
  enabled: true
  #Messages of /toggledeathmsgs
  muted: "&bYou won't see death messages anymore."
  unmuted: "&bYou now will see death messages."

#Random spawn configuration if the player doesn't have a bed
random-spawn:
  enabled: true
  #World to respawn in
  world-name: "world"
  #Sets of coordinates to setup random spawn
  minX: -500
  minZ: -500
  maxX: 500
  maxZ: 500

#SalC1 dupe configuration
salc1-dupe:
  #Turn this on if you want to enable SalC1 dupe.
  enabled: true
  message: "&cPlacing chests on entities is currently disabled to prevent duplication exploits."

#Pistonm Dupe configuration
piston-dupe:
  #Turn this on if you want to enable piston dupe.
  enabled: true
  #Amount of shulkers clonated per dupe
  amount: 3

#Help Command
help-command:
  - "&5---------------------------------------------------"
  - "&6/ignore &7- ignores a player."
  - "&6/ignorelist &7- lists ignored players."
  - "&6/r &7- replies to a player."
  - "&6/msg &7- messages a player."
  - "&6/toggledeathmsgs &7- toggles all death messages."
  - "&6/tps &7- gets current TPS (ticks per second)."
  - "&6/kill &7- kills you."
  - "&6/ping &7- shows your ping."
  - "&6/bed &7- locates your current bed coordinates."
  - "&6/joindate &7- lets you see someone's join date."
  - "&6/stats &7- shows you information about the server."
  - "&6/discord &7- joins our Discord server."
  - "&6/nc &7- changes the color of your nickname in chat."
  - "&5-----------------------------------------------------"

#Stats Command
#You can use different placeholders like <online> and <discord>
stats-command:
  - "&5---------------------------------------------------"
  - "&7Change this on config.yml"
  - "&6Online players &7- &6<online>"
  - "&6Server version &7- &61.12.2"
  - "&6World seed &7- &67379634448549082222"
  - "&6Discord &7- &6<discord>"
  - "&5-----------------------------------------------------"

#/bed command messages
bed-command:
  message-bed: "&3Your bed is currently located at &6x<x>&3, &6y<y>&3, &6z<z>&3."
  message-nobed: "&3You currently don't have a bed set."

#/nc command messages
nc-command:
  usage-message: "&7Use /nc <color> or /nc <format>.\n
  List of color codes: &0black&7, &1darkblue&7, &2darkgreen&7, &3darkaqua&7, &4red&7, &5darkpurple&7, &6gold&7, &7gray&7, &8darkgray&7, &9blue&7, &agreen&7, &baqua&7, &dlightpurple&7, &eyellow&7, &fwhite&7.\n
  List of formatting codes: &lbold&7, &r&kIII&r magic &kIII&r&7, &nunderline&7, &mstrike&7, &oitalic&7.\n
  Use /nc reset to reset your nickname."
  error-message: "&cSpecified color doesn't exist!"
  success-message: "&7You have changed your nickname color to &6<color>&7!"
  reset-message: "&7Your color nickname has been reset successfully!"

#/corereload command messages
core-reload:
  message-reload: "&3Plugin has been reloaded!"

#/ping command
ping:
  ping-msg: "&bYour ping is &6&l<ping>ms&r&b."
  ping-other: "&b<p>'s ping is &6&l<ping>ms&r&b."
  ping-notonline: "&bThe player doesn't exist or is not online."

#/joindate
joindate:
  joindate-msg: "&bYou joined this server for the first time on &6&l<jd>"
  joindate-notonline: "&bThe player doesn't exist or is not online."
  joindate-other: "&b<p> joined this server for the first time on &6&l<jd>"

#Anti-nether-roof config
antinetherroof:
  disable-netherroof: true
  disabled-message: "&cNether roof is currently disabled."
  nether-worldname: "world_nether"
  max-y-level: 125

#Anti-nether-bottom config
antinetherbottom:
  disable-netherbottom: true
  disabled-message: "&cNether bottom is currently disabled"
  nether-worldname: "world_nether"
  min-y-level: 1

#AntiDispenserCrash
antidispensercrash:
  enabled: true
  loginconsole: true

#AntiBlockPlaces
antiblockplaces:
  enabled: true
  blocks:
    bedrock: true
    endportalframes: true
    barriers: true
    spawners: false

#If enabled, 32k won't dealt damage
32kpatch:
  enabled: true